### ISSUE TITLE
TODO - Accounts

### ISSUE THREAD

**Issue by Cuel** [fparma/fparma-web#1]
- [x] Redirect to steam login for users
- [x] Handle callback from steam
- [x] Once user is logged it, must select a username
- [x] If user does exits, load user to session
- [ ] Let user change avatar?
- [ ] Write tests
