### ISSUE TITLE
TODO - Events

### ISSUE THREAD

**Issue by Cuel** [fparma/fparma-web#2]
- [x] Event DB model
- Permalink (type - slots - name)
- Type
- Name
- Time & date
- Info (description)
- Slots (flat or deep?)
- [x] Express routes for admins (create, update, delete). 
  - How to handle update in regards to slots (add/remove?)
- [x] Express route to read for normal users
- [x] Express route to add and remove signup
- [x] Express route for admins to signup or remove users
- [ ] Tests
